Create basic obstacle avoidance sketch
DIT112-V20/group-06 pull request #13
Opened 2020-04-02 14:28 UTC by FayonaC

Created basic sketch to make the SmartCar stop moving forwards before it collides with an obstacle.

Code is taken from Dimitrios Platis' platform workshop 2020-04-01.

Resolves: #9

2020-04-02 14:31 UTC, platisd approved these changes
Minor (style) suggestion, otherwise it looks correct.
Just keep in mind that once there is no more obstacle in the way, the car will start moving again.

2020-04-02 14:31 UTC, platisd commented on src/car/avoid/avoid.ino
> +    if (distance && distance < 20){
It is considered a good practice unless a variable is a boolean, to be explicit about it. Namely in this case `distance != 0`

2020-04-06 08:33 UTC, JenniNord requested changes
Make the suggested change before approval.

2020-04-06 08:40 UTC, Victori4 approved these changes
Good style improvement distance in if statement

2020-04-06 08:40 UTC, JenniNord approved these changes

2020-04-06 08:42 UTC, merged